/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kode_project;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author riand
 */
public class quizsoal extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
int absen_siswa = 0;
    public quizsoal(String QuizID, int absen_siswa) {
        initComponents();
        
        this.absen_siswa = absen_siswa;
        try {
        String sql = "SELECT * FROM question WHERE QuizID = ?";
        java.sql.Connection conn = (java.sql.Connection) koneksi.koneksiDB();
        PreparedStatement psmt = conn.prepareStatement(sql);
        psmt.setString(1, QuizID);
        ResultSet rs = psmt.executeQuery();

        int nomor_soal = 0;
        while (rs.next()) {
            nomor_soal++;
        }

        nomor_soal++; // Menambahkan 1 karena nomor soal baru

        String str = String.valueOf(nomor_soal);
        nomorSoalTXT.setText(str);

        QuizIdTXT.setText(QuizID);
    } catch (Exception e) {
        JOptionPane.showConfirmDialog(this, e);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        QuestionTXT = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Opt1TXT = new javax.swing.JTextField();
        Opt2TXT = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Opt3TXT = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Opt4TXT = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        AnswerTXT = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        nomorSoalTXT = new javax.swing.JLabel();
        QuizIdTXT = new javax.swing.JLabel();
        saveBut = new javax.swing.JButton();
        clearBut = new javax.swing.JButton();
        ExitBut = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        exitBut1 = new javax.swing.JButton();

        jLabel10.setText("jLabel10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 255, 204));

        jLabel1.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        jLabel1.setText("Quiz ID :");

        jLabel2.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        jLabel2.setText("Nomor Soal :");

        jLabel4.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        jLabel4.setText("Question :");

        jLabel5.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        jLabel5.setText("Option 1 :");

        jLabel6.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        jLabel6.setText("Option 2 :");

        Opt3TXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Opt3TXTActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        jLabel7.setText("Option 3 :");

        jLabel8.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        jLabel8.setText("Option 4 :");

        jLabel9.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        jLabel9.setText("Answer :");

        nomorSoalTXT.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        nomorSoalTXT.setText("00");

        QuizIdTXT.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        QuizIdTXT.setText("00");

        saveBut.setBackground(new java.awt.Color(0, 153, 153));
        saveBut.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        saveBut.setText("Save");
        saveBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButActionPerformed(evt);
            }
        });

        clearBut.setBackground(new java.awt.Color(0, 153, 153));
        clearBut.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        clearBut.setText("Clear");
        clearBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(QuizIdTXT))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(nomorSoalTXT))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(QuestionTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(18, 18, 18)
                            .addComponent(Opt3TXT, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AnswerTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(Opt4TXT, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Opt1TXT, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(Opt2TXT, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(saveBut, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearBut, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(565, 565, 565)))
                .addContainerGap(294, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(QuizIdTXT))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nomorSoalTXT))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(QuestionTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Opt1TXT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Opt2TXT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Opt3TXT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Opt4TXT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(AnswerTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBut, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearBut, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 111, 1184, 660));

        ExitBut.setBackground(new java.awt.Color(255, 153, 51));
        ExitBut.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        ExitBut.setText("EXIT");
        ExitBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButActionPerformed(evt);
            }
        });
        jPanel1.add(ExitBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 20, 137, 73));

        jButton3.setBackground(new java.awt.Color(255, 153, 51));
        jButton3.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        jButton3.setText("EXIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 20, 137, 73));

        jLabel3.setFont(new java.awt.Font("Montserrat", 0, 48)); // NOI18N
        jLabel3.setText("New Quiz");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 20, -1, -1));

        exitBut1.setBackground(new java.awt.Color(255, 153, 51));
        exitBut1.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        exitBut1.setText("EXIT");
        exitBut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBut1ActionPerformed(evt);
            }
        });
        jPanel1.add(exitBut1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 20, 137, 73));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButActionPerformed
        int a = JOptionPane.showConfirmDialog(this, "Are you sure want to save?", "Select", JOptionPane.OK_CANCEL_OPTION);
        if (a == 0) {
            try {
                String ID = QuizIdTXT.getText();
                String nomor = nomorSoalTXT.getText();
                int nomorINT = Integer.parseInt(nomor);
                String question = QuestionTXT.getText();
                String opt1 = Opt1TXT.getText();
                String opt2 = Opt2TXT.getText();
                String opt3 = Opt3TXT.getText();
                String opt4 = Opt4TXT.getText();
                String answer = AnswerTXT.getText();
                
                 java.sql.Connection conn = (java.sql.Connection) koneksi.koneksiDB();
                 PreparedStatement psmt = conn.prepareStatement("INSERT INTO question(QuizID, nomor_soal, Question, OptionA, OptionB, OptionC, OptionD, CorrectAnswer) VALUES(?,?,?,?,?,?,?,?)");
                 psmt.setString(1, ID);
                 psmt.setInt(2, nomorINT);
                 psmt.setString(3, question);
                 psmt.setString(4, opt1);
                 psmt.setString(5, opt2);
                 psmt.setString(6, opt3);
                 psmt.setString(7, opt4);
                 psmt.setString(8, answer);
                 psmt.execute();
                 JOptionPane.showConfirmDialog(this, "Succes Tambah Soal");
                  this.dispose();
                 new quizsoal(ID,absen_siswa).setVisible(true);
                 
            } catch (Exception e) {
                JOptionPane.showConfirmDialog(this, e);
                System.out.print(e);
            }
        }

    }//GEN-LAST:event_saveButActionPerformed

    private void ExitButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButActionPerformed
         int a = JOptionPane.showConfirmDialog(this, "Are you sure want to save?", "Select", JOptionPane.OK_CANCEL_OPTION);
         if (a == 0){
             this.dispose();
             new dash_admin(absen_siswa).setVisible(true);
         }
    }//GEN-LAST:event_ExitButActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void exitBut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBut1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitBut1ActionPerformed

    private void clearButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButActionPerformed
        QuestionTXT.setText("");
        Opt1TXT.setText("");
        Opt2TXT.setText("");
        Opt3TXT.setText("");
        Opt4TXT.setText("");
        AnswerTXT.setText("");
    }//GEN-LAST:event_clearButActionPerformed

    private void Opt3TXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Opt3TXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Opt3TXTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quizsoal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quizsoal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quizsoal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quizsoal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new quizsoal("0",0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AnswerTXT;
    private javax.swing.JButton ExitBut;
    private javax.swing.JTextField Opt1TXT;
    private javax.swing.JTextField Opt2TXT;
    private javax.swing.JTextField Opt3TXT;
    private javax.swing.JTextField Opt4TXT;
    private javax.swing.JTextField QuestionTXT;
    private javax.swing.JLabel QuizIdTXT;
    private javax.swing.JButton clearBut;
    private javax.swing.JButton exitBut1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel nomorSoalTXT;
    private javax.swing.JButton saveBut;
    // End of variables declaration//GEN-END:variables
}
